/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SearchRouteImport } from './routes/search'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsDbHashSessionIdRouteImport } from './routes/sessions_.$dbHash.$sessionId'
import { Route as KnowledgeDbHashSourceIdRouteImport } from './routes/knowledge_.$dbHash.$sourceId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsDbHashSessionIdRoute = SessionsDbHashSessionIdRouteImport.update({
  id: '/sessions_/$dbHash/$sessionId',
  path: '/sessions/$dbHash/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeDbHashSourceIdRoute = KnowledgeDbHashSourceIdRouteImport.update({
  id: '/knowledge_/$dbHash/$sourceId',
  path: '/knowledge/$dbHash/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/knowledge': typeof KnowledgeRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/knowledge/$dbHash/$sourceId': typeof KnowledgeDbHashSourceIdRoute
  '/sessions/$dbHash/$sessionId': typeof SessionsDbHashSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/knowledge': typeof KnowledgeRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/knowledge/$dbHash/$sourceId': typeof KnowledgeDbHashSourceIdRoute
  '/sessions/$dbHash/$sessionId': typeof SessionsDbHashSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enterprise': typeof EnterpriseRoute
  '/knowledge': typeof KnowledgeRoute
  '/search': typeof SearchRoute
  '/sessions': typeof SessionsRoute
  '/knowledge_/$dbHash/$sourceId': typeof KnowledgeDbHashSourceIdRoute
  '/sessions_/$dbHash/$sessionId': typeof SessionsDbHashSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enterprise'
    | '/knowledge'
    | '/search'
    | '/sessions'
    | '/knowledge/$dbHash/$sourceId'
    | '/sessions/$dbHash/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enterprise'
    | '/knowledge'
    | '/search'
    | '/sessions'
    | '/knowledge/$dbHash/$sourceId'
    | '/sessions/$dbHash/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/enterprise'
    | '/knowledge'
    | '/search'
    | '/sessions'
    | '/knowledge_/$dbHash/$sourceId'
    | '/sessions_/$dbHash/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnterpriseRoute: typeof EnterpriseRoute
  KnowledgeRoute: typeof KnowledgeRoute
  SearchRoute: typeof SearchRoute
  SessionsRoute: typeof SessionsRoute
  KnowledgeDbHashSourceIdRoute: typeof KnowledgeDbHashSourceIdRoute
  SessionsDbHashSessionIdRoute: typeof SessionsDbHashSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions_/$dbHash/$sessionId': {
      id: '/sessions_/$dbHash/$sessionId'
      path: '/sessions/$dbHash/$sessionId'
      fullPath: '/sessions/$dbHash/$sessionId'
      preLoaderRoute: typeof SessionsDbHashSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge_/$dbHash/$sourceId': {
      id: '/knowledge_/$dbHash/$sourceId'
      path: '/knowledge/$dbHash/$sourceId'
      fullPath: '/knowledge/$dbHash/$sourceId'
      preLoaderRoute: typeof KnowledgeDbHashSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnterpriseRoute: EnterpriseRoute,
  KnowledgeRoute: KnowledgeRoute,
  SearchRoute: SearchRoute,
  SessionsRoute: SessionsRoute,
  KnowledgeDbHashSourceIdRoute: KnowledgeDbHashSourceIdRoute,
  SessionsDbHashSessionIdRoute: SessionsDbHashSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
